name: Update GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"  # Daily
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update_stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update stats
        uses: anuraghazra/github-readme-stats@latest
        with:
          theme: tokyonight
          show_icons: true
          count_private: true
          
      - name: Commit changes
        run: |
          git config --global user.name "Paul Alfredo"
          git config --global user.email "ton@email.com"
          git add .
          git commit -m "📊 Update GitHub stats"
          git push